### ISSUE TITLE
Certificate Rejected

### ISSUE THREAD

**Issue by Thibaut-H** [copercini/esp8266-aws_iot#12]
I feel like I've tried everything, but I can't seem to figure out my error with the code.
I made sure the certificates had a policy allowing full access to aws and attached it to a thing that I changed in the code, but I keep getting disconnected with random, quickly dropped connections.
https://iot.stackexchange.com/questions/3516/aws-iot-certificate-rejection

**Comment by copercini** [comment]
You can try with a desktop MQTT client, like [MQTT.fx](http://www.fhilitski.com/2016/09/connecting-mqtt-fx-to-aws-iot/) or [Paho MQTT spy](https://github.com/eclipse/paho.mqtt-spy/wiki/FAQs)

If it connects and works, the problem is in ESP8266 side, if it doesn't work even on desktop, so is a policy or AWS configuration

**Comment by Thibaut-H** [comment]
Hi, thank you very much for the suggestion. I managed to get the MQTT.fx working once I used the AmazonRootCA1 instead of the legacy certificate suggested. I then commented out the loading of the ca.der file after converting Amazon's file using: 
`$ openssl x509 -in AmazonRootCA1.pem -out ca.der -outform DER `
I can now successfully publish to AWS IoT and will try with a user generated CA as this is what I will be eventually needing, but I assume it should work similarly. Thank you again for your time!
